# Generated by Django 5.2.17 on 2026-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
