# Generated by Django 5.2.17 on 2026-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('ultimo_numero', models.BigIntegerField(default=0)),
            ],
        ),
    ]
