# Generated by Django 5.2.17 on 2026-10-07 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoe_personalizadas', to='clientes.cliente')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
