# Generated by Django 5.2.17 on 2026-10-07 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('orcamentos', '0002_solicitacaopersonalizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('cliente_nome_snapshot', models.CharField(max_length=150)),
                ('cliente_documento_snapshot', models.CharField(max_length=14)),
                ('cliente_email_snapshot', models.EmailField(max_length=254)),
                ('cliente_telefone_snapshot', models.CharField(max_length=20)),
                ('endereco_snapshot', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.TextField()),
                ('validade', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamento', to='clientes.cliente')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
