# Generated by Django 5.2.17 on 2026-10-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_orcamento'),
        ('produtos', '0002_produtoimagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo_snapshot', models.CharField(max_length=50)),
                ('produto_nome_snapshot', models.CharField(max_length=150)),
                ('especificacoes_snapshot', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='produtos.produto')),
            ],
        ),
    ]
