# Generated by Django 5.2.17 on 2026-10-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('altura_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profundidade_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=150)),
                ('espressura_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(max_length=150)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
            ],
        ),
    ]
