# Generated by Django 5.2.17 on 2026-10-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=100)),
                ('registro_id', models.CharField(max_length=100)),
                ('dados_alterado', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
